CREATE DATABASE IF NOT EXISTS camp_db;
USE camp_db;

CREATE TABLE IF NOT EXISTS roles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    role ENUM('admin', 'customer') NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(150) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    phoneNumber VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    activeStatus BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    roleId INT NOT NULL,
    CONSTRAINT fk_user_role FOREIGN KEY (roleId) REFERENCES roles(id)
);